# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_staging_meg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 821, 621))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ControlPanelLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.ControlPanelLayoutWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ControlPanelLayoutWidget.sizePolicy().hasHeightForWidth())
        self.ControlPanelLayoutWidget.setSizePolicy(sizePolicy)
        self.ControlPanelLayoutWidget.setObjectName("ControlPanelLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ControlPanelLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FileDrop = QtWidgets.QGroupBox(self.ControlPanelLayoutWidget)
        self.FileDrop.setAcceptDrops(True)
        self.FileDrop.setToolTip("Drop files here")
        self.FileDrop.setObjectName("FileDrop")
        self.horizontalLayout.addWidget(self.FileDrop)
        self.widget = QtWidgets.QWidget(self.ControlPanelLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CheckData = QtWidgets.QPushButton(self.widget)
        self.CheckData.setObjectName("CheckData")
        self.verticalLayout_2.addWidget(self.CheckData)
        self.LaunchBidsCreator = QtWidgets.QPushButton(self.widget)
        self.LaunchBidsCreator.setObjectName("LaunchBidsCreator")
        self.verticalLayout_2.addWidget(self.LaunchBidsCreator)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addWidget(self.ControlPanelLayoutWidget)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 455))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FileDrop.setTitle(_translate("MainWindow", "Drag/Drop Files"))
        self.CheckData.setToolTip(_translate("MainWindow", "Runs Minimal Checks on the Data"))
        self.CheckData.setText(_translate("MainWindow", "Check Data"))
        self.LaunchBidsCreator.setText(_translate("MainWindow", "Open BIDS creator"))
    
    # def read_drops(self):
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
