# Form implementation generated from reading ui file 'nih2mne/GUI/templates/input_error_dset_tile_listWidgetBase.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from nih2mne.GUI.qt_compat import QtCore, QtGui, QtWidgets


class Ui_ErrorDatasetTile(object):
    def setupUi(self, ErrorDatasetTile):
        ErrorDatasetTile.setObjectName("ErrorDatasetTile")
        ErrorDatasetTile.resize(845, 62)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ErrorDatasetTile.sizePolicy().hasHeightForWidth())
        ErrorDatasetTile.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ErrorDatasetTile)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=ErrorDatasetTile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ReadoutFilename = QtWidgets.QLabel(parent=self.widget)
        self.ReadoutFilename.setObjectName("ReadoutFilename")
        self.horizontalLayout.addWidget(self.ReadoutFilename)
        self.pb_ReviewError = QtWidgets.QPushButton(parent=self.widget)
        self.pb_ReviewError.setObjectName("pb_ReviewError")
        self.horizontalLayout.addWidget(self.pb_ReviewError)
        self.pb_DeleteTile = QtWidgets.QPushButton(parent=self.widget)
        self.pb_DeleteTile.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_DeleteTile.sizePolicy().hasHeightForWidth())
        self.pb_DeleteTile.setSizePolicy(sizePolicy)
        self.pb_DeleteTile.setStyleSheet("color: rgb(224, 27, 36);")
        self.pb_DeleteTile.setObjectName("pb_DeleteTile")
        self.horizontalLayout.addWidget(self.pb_DeleteTile)
        self.verticalLayout.addWidget(self.widget)
        self.lbl_Status = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Status.sizePolicy().hasHeightForWidth())
        self.lbl_Status.setSizePolicy(sizePolicy)
        self.lbl_Status.setObjectName("lbl_Status")
        self.verticalLayout.addWidget(self.lbl_Status)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(ErrorDatasetTile)
        QtCore.QMetaObject.connectSlotsByName(ErrorDatasetTile)

    def retranslateUi(self, ErrorDatasetTile):
        _translate = QtCore.QCoreApplication.translate
        ErrorDatasetTile.setWindowTitle(_translate("ErrorDatasetTile", "Form"))
        self.ReadoutFilename.setText(_translate("ErrorDatasetTile", "(ERROR) Filename"))
        self.pb_ReviewError.setText(_translate("ErrorDatasetTile", "Review Error Code"))
        self.pb_DeleteTile.setText(_translate("ErrorDatasetTile", "X"))
        self.lbl_Status.setText(_translate("ErrorDatasetTile", "Status:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ErrorDatasetTile = QtWidgets.QWidget()
    ui = Ui_ErrorDatasetTile()
    ui.setupUi(ErrorDatasetTile)
    ErrorDatasetTile.show()
    sys.exit(app.exec())
