# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parse_marks_single_line.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1048, 43)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(2, 4, 2, 4)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.combo_LeadSelection = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_LeadSelection.sizePolicy().hasHeightForWidth())
        self.combo_LeadSelection.setSizePolicy(sizePolicy)
        self.combo_LeadSelection.setObjectName("combo_LeadSelection")
        self.combo_LeadSelection.addItem("")
        self.horizontalLayout.addWidget(self.combo_LeadSelection)
        self.cb_OnLead = QtWidgets.QCheckBox(Form)
        self.cb_OnLead.setObjectName("cb_OnLead")
        self.horizontalLayout.addWidget(self.cb_OnLead)
        self.combo_LagSelection = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_LagSelection.sizePolicy().hasHeightForWidth())
        self.combo_LagSelection.setSizePolicy(sizePolicy)
        self.combo_LagSelection.setObjectName("combo_LagSelection")
        self.combo_LagSelection.addItem("")
        self.horizontalLayout.addWidget(self.combo_LagSelection)
        self.cb_OnLag = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_OnLag.sizePolicy().hasHeightForWidth())
        self.cb_OnLag.setSizePolicy(sizePolicy)
        self.cb_OnLag.setObjectName("cb_OnLag")
        self.horizontalLayout.addWidget(self.cb_OnLag)
        self.lbl_StartOffset = QtWidgets.QLabel(Form)
        self.lbl_StartOffset.setObjectName("lbl_StartOffset")
        self.horizontalLayout.addWidget(self.lbl_StartOffset)
        self.te_StartOffset = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_StartOffset.sizePolicy().hasHeightForWidth())
        self.te_StartOffset.setSizePolicy(sizePolicy)
        self.te_StartOffset.setMinimumSize(QtCore.QSize(70, 0))
        self.te_StartOffset.setMaximumSize(QtCore.QSize(100, 16777215))
        self.te_StartOffset.setObjectName("te_StartOffset")
        self.horizontalLayout.addWidget(self.te_StartOffset)
        self.lbl_StopOffset = QtWidgets.QLabel(Form)
        self.lbl_StopOffset.setObjectName("lbl_StopOffset")
        self.horizontalLayout.addWidget(self.lbl_StopOffset)
        self.te_StopOffset = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_StopOffset.sizePolicy().hasHeightForWidth())
        self.te_StopOffset.setSizePolicy(sizePolicy)
        self.te_StopOffset.setMinimumSize(QtCore.QSize(70, 0))
        self.te_StopOffset.setMaximumSize(QtCore.QSize(100, 16777215))
        self.te_StopOffset.setObjectName("te_StopOffset")
        self.horizontalLayout.addWidget(self.te_StopOffset)
        self.lbl_MrkName = QtWidgets.QLabel(Form)
        self.lbl_MrkName.setObjectName("lbl_MrkName")
        self.horizontalLayout.addWidget(self.lbl_MrkName)
        self.te_MrkName = QtWidgets.QLineEdit(Form)
        self.te_MrkName.setObjectName("te_MrkName")
        self.horizontalLayout.addWidget(self.te_MrkName)
        self.pb_Check = QtWidgets.QPushButton(Form)
        self.pb_Check.setObjectName("pb_Check")
        self.horizontalLayout.addWidget(self.pb_Check)
        self.pb_DeleteLine = QtWidgets.QPushButton(Form)
        self.pb_DeleteLine.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_DeleteLine.setFont(font)
        self.pb_DeleteLine.setObjectName("pb_DeleteLine")
        self.horizontalLayout.addWidget(self.pb_DeleteLine)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.combo_LeadSelection.setItemText(0, _translate("Form", "--LeadEvt--"))
        self.cb_OnLead.setText(_translate("Form", "MrkOnLead"))
        self.combo_LagSelection.setItemText(0, _translate("Form", "--LagEvt--"))
        self.cb_OnLag.setText(_translate("Form", "MrkOnLag"))
        self.lbl_StartOffset.setText(_translate("Form", "startOffset (s)"))
        self.lbl_StopOffset.setText(_translate("Form", "stopOffset (s)"))
        self.lbl_MrkName.setText(_translate("Form", "MrkName"))
        self.pb_Check.setText(_translate("Form", "N=?"))
        self.pb_DeleteLine.setText(_translate("Form", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
