# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trigger_single_line.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(920, 43)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_ChannelName = QtWidgets.QLabel(Form)
        self.lbl_ChannelName.setObjectName("lbl_ChannelName")
        self.horizontalLayout.addWidget(self.lbl_ChannelName)
        self.cb_Up = QtWidgets.QCheckBox(Form)
        self.cb_Up.setObjectName("cb_Up")
        self.horizontalLayout.addWidget(self.cb_Up)
        self.cb_Down = QtWidgets.QCheckBox(Form)
        self.cb_Down.setObjectName("cb_Down")
        self.horizontalLayout.addWidget(self.cb_Down)
        self.lbl_EvtName = QtWidgets.QLabel(Form)
        self.lbl_EvtName.setObjectName("lbl_EvtName")
        self.horizontalLayout.addWidget(self.lbl_EvtName)
        self.te_EvtName = QtWidgets.QLineEdit(Form)
        self.te_EvtName.setObjectName("te_EvtName")
        self.horizontalLayout.addWidget(self.te_EvtName)
        self.lbl_EvtCount = QtWidgets.QLabel(Form)
        self.lbl_EvtCount.setObjectName("lbl_EvtCount")
        self.horizontalLayout.addWidget(self.lbl_EvtCount)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_ChannelName.setText(_translate("Form", "ChanName"))
        self.cb_Up.setText(_translate("Form", "Up"))
        self.cb_Down.setText(_translate("Form", "Down"))
        self.lbl_EvtName.setText(_translate("Form", "Event name:"))
        self.lbl_EvtCount.setText(_translate("Form", "N="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
