# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trigger_single_line.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(920, 43)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_ChannelName = QtWidgets.QLabel(Form)
        self.lbl_ChannelName.setObjectName("lbl_ChannelName")
        self.horizontalLayout.addWidget(self.lbl_ChannelName)
        self.cb_Up = QtWidgets.QCheckBox(Form)
        self.cb_Up.setObjectName("cb_Up")
        self.horizontalLayout.addWidget(self.cb_Up)
        self.cb_Down = QtWidgets.QCheckBox(Form)
        self.cb_Down.setObjectName("cb_Down")
        self.horizontalLayout.addWidget(self.cb_Down)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cb_HistUp = QtWidgets.QCheckBox(Form)
        self.cb_HistUp.setObjectName("cb_HistUp")
        self.horizontalLayout.addWidget(self.cb_HistUp)
        self.lbl_EvtName = QtWidgets.QLabel(Form)
        self.lbl_EvtName.setObjectName("lbl_EvtName")
        self.horizontalLayout.addWidget(self.lbl_EvtName)
        self.te_EvtName = QtWidgets.QLineEdit(Form)
        self.te_EvtName.setObjectName("te_EvtName")
        self.horizontalLayout.addWidget(self.te_EvtName)
        spacerItem1 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lbl_EvtCount = QtWidgets.QLabel(Form)
        self.lbl_EvtCount.setObjectName("lbl_EvtCount")
        self.horizontalLayout.addWidget(self.lbl_EvtCount)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_ChannelName.setText(_translate("Form", "ChanName"))
        self.cb_Up.setToolTip(_translate("Form", "<html><head/><body><p>Evaluate on rising edge of trigger pulse</p></body></html>"))
        self.cb_Up.setText(_translate("Form", "Up"))
        self.cb_Down.setToolTip(_translate("Form", "<html><head/><body><p>Evaluate on the down-going edge of the trigger</p></body></html>"))
        self.cb_Down.setText(_translate("Form", "Down"))
        self.cb_HistUp.setToolTip(_translate("Form", "<html><head/><body><p>Some protocols produce projector polarity that is ambiguous run to run. This selection will force the polarity to be assessed and assumes that the projector trigger value is off most of the time. This gaurantees that what you have set will work for all of your data.</p></body></html>"))
        self.cb_HistUp.setText(_translate("Form", "(ForceMinUp)"))
        self.lbl_EvtName.setText(_translate("Form", "Event name:"))
        self.lbl_EvtCount.setToolTip(_translate("Form", "<html><head/><body><p>Number of events evaluated from trigger line</p></body></html>"))
        self.lbl_EvtCount.setText(_translate("Form", "N="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
