#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""

Autogenerated code from:
Beamformer Template: v0.1.0
nih2mne Version: <<VER>>
Date (script gen): <<DATE>>

@author: jstout211
"""

import sys
import logging
import mne
import os, os.path as op
import numpy as np
import glob
import pickle
import copy 
from mne.beamformer import make_lcmv, apply_lcmv, apply_lcmv_epochs, apply_lcmv_raw
from mne.datasets import fetch_fsaverage
import pandas as pd
from mne.beamformer import apply_lcmv_cov    
import nibabel as nb
import mne_bids
from mne_bids import BIDSPath
import pathlib
import copy
from mne.preprocessing import annotate_muscle_zscore
from autoreject import AutoReject

if "SLURM_JOB_ID" in os.environ:
    n_jobs = int(os.environ.get("SLURM_CPUS_PER_TASK", "1"))
else:
    n_jobs = -1

#%% << INSERT GUI COMPONENTS HERE >>



#%% Define Paths

bids_path = BIDSPath(root=bids_root, 
                     subject=subject,
                     run=run, 
                     session=ses, 
                     task=task_type, 
                     datatype='meg')

anat_bids_path = BIDSPath(root=bids_root, subject=subject, datatype='anat',
                          extension='.nii.gz', acquisition = None, 
                          suffix = 'T1w', session = ses)

deriv_path = bids_path.copy().update(root= bids_path.root / 'derivatives',
                                     check=False)
preprocessing_path = deriv_path.copy().update(root = deriv_path.root / 'preproc')
#Create temp structure to force the fpath creation (requires suffix+extension) to gen parent
_ = preprocessing_path.copy().update(suffix='meg',extension='.ds').fpath.parent.mkdir(parents=True, exist_ok=True)

output_path = deriv_path.copy().update(root = deriv_path.root / project)
#Create temp structure to force the fpath creation (requires suffix+extension) to gen parent
_ = output_path.copy().update(suffix='meg',extension='.ds').fpath.parent.mkdir(parents=True, exist_ok=True)

log_dir = output_path.root / 'logging' / f'sub-{bids_path.subject}'
log_dir.mkdir(parents=True, exist_ok=True)
log_fname = log_dir / 'beamformer_template.log'

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
logger.handlers.clear()
_log_handler = logging.FileHandler(log_fname)
_log_handler.setFormatter(
    logging.Formatter('%(asctime)s %(levelname)s %(message)s')
)
logger.addHandler(_log_handler)
logger.propagate = False

subjects_dir = deriv_path.root / 'freesurfer' / 'subjects'
fs_subject = 'sub-'+bids_path.subject

raw_fname = bids_path.copy() 
noise_fname = bids_path.copy().update(task='EmptyRoom', run=er_run)

bem_fname = preprocessing_path.copy().update(suffix='bem', extension='.fif', 
                                             run=None)
src_fname = preprocessing_path.copy().update(suffix='src', extension='.fif', 
                                             run=None)
trans_fname = preprocessing_path.copy().update(suffix='trans',extension='.fif', 
                                               run=None)
fwd_fname = preprocessing_path.copy().update(suffix='fwd', extension='.fif')


raw_load_opts = dict(system_clock = 'ignore', clean_names =True, 
                          preload=True)
raw = mne.io.read_raw_ctf(raw_fname.fpath, **raw_load_opts)
if not noise_fname.fpath.exists():
    logger.error(f'Noise file does not exist: {noise_fname.fpath}')
noise_raw = mne.io.read_raw_ctf(noise_fname.fpath, **raw_load_opts)
logger.info(f'Loaded raw data from: {raw_fname.fpath}')
logger.info(f'Loaded noise data from: {noise_fname.fpath}')
#Add data cropping here to remove zeros


def get_make_bem_solution(bem_fname, fs_subject, subjects_dir, logger):
    try:
        if bem_fname.fpath.exists():
            logger.info(f'Using previously created BEM solution: {bem_fname.fpath}')
            bem_sol = mne.read_bem_solution(bem_fname)
        else:
            logger.info(f'Creating BEM solution: {bem_fname.fpath}')
            mne.bem.make_watershed_bem(fs_subject, subjects_dir=subjects_dir, overwrite=True)
            bem = mne.make_bem_model(fs_subject, subjects_dir=subjects_dir,
                                     conductivity=[0.3])
            bem_sol = mne.make_bem_solution(bem)
            mne.write_bem_solution(bem_fname.fpath, bem_sol, overwrite=True)
        return bem_sol
    except Exception as err:
        logger.exception(f'Failed to get or make BEM solution: {bem_fname.fpath}')
        raise RuntimeError(f'Failed to get or make BEM solution: {bem_fname.fpath}') from err


def get_make_source_space(src_fname, fs_subject, subjects_dir, logger):
    try:
        if src_fname.fpath.exists():
            logger.info(f'Using previously created source space: {src_fname.fpath}')
            src = mne.read_source_spaces(src_fname.fpath)
        else:
            logger.info(f'Creating source space: {src_fname.fpath}')
            src = mne.setup_source_space(fs_subject, spacing='oct6', add_dist='patch',
                                         subjects_dir=subjects_dir)
            src.save(src_fname.fpath, overwrite=True)
        return src
    except Exception as err:
        logger.exception(f'Failed to get or make source space: {src_fname.fpath}')
        raise RuntimeError(f'Failed to get or make source space: {src_fname.fpath}') from err


def get_make_trans(trans_fname, bids_path, anat_bids_path, fs_subject, subjects_dir, logger):
    try:
        if trans_fname.fpath.exists():
            logger.info(f'Using previously created transform: {trans_fname.fpath}')
            trans = mne.read_trans(trans_fname.fpath)
        else:
            logger.info(f'Creating transform: {trans_fname.fpath}')
            trans = mne_bids.read.get_head_mri_trans(
                bids_path,
                extra_params=dict(system_clock='ignore'),
                t1_bids_path=anat_bids_path,
                fs_subject=fs_subject,
                fs_subjects_dir=subjects_dir,
            )
            mne.write_trans(trans_fname.fpath, trans, overwrite=True)
        return trans
    except Exception as err:
        logger.exception(f'Failed to get or make transform: {trans_fname.fpath}')
        raise RuntimeError(f'Failed to get or make transform: {trans_fname.fpath}') from err


def get_make_forward_solution(fwd_fname, raw, trans, src, bem_sol, n_jobs, logger):
    try:
        if fwd_fname.fpath.exists():
            logger.info(f'Using previously created forward solution: {fwd_fname.fpath}')
            fwd = mne.read_forward_solution(fwd_fname)
        else:
            logger.info(f'Creating forward solution: {fwd_fname.fpath}')
            fwd = mne.make_forward_solution(raw.info, trans, src, bem_sol, eeg=False,
                                            n_jobs=n_jobs)
            mne.write_forward_solution(fwd_fname.fpath, fwd, overwrite=True)
        return fwd
    except Exception as err:
        logger.exception(f'Failed to get or make forward solution: {fwd_fname.fpath}')
        raise RuntimeError(
            f'Failed to get or make forward solution: {fwd_fname.fpath}'
        ) from err




#%% Load or create any MRI related items
bem_sol = get_make_bem_solution(bem_fname, fs_subject, subjects_dir, logger)
src = get_make_source_space(src_fname, fs_subject, subjects_dir, logger)
trans = get_make_trans(trans_fname, bids_path, anat_bids_path, fs_subject,
                       subjects_dir, logger)
fwd = get_make_forward_solution(fwd_fname, raw, trans, src, bem_sol, n_jobs, logger)
    
#%% Preproc Raw data
if use_muscle_detection:
    _musc_annot = annotate_muscle_zscore(raw, threshold=4, ch_type='mag', min_length_good=0.1, 
                       filter_freq=(110, 140), n_jobs=n_jobs, verbose=None)
    raw.set_annotations(raw.annotations + _musc_annot[0])

raw.filter(f_min, f_max, n_jobs=n_jobs)
noise_raw.filter(f_min, f_max, n_jobs=n_jobs)

raw.notch_filter([60,120,180], n_jobs=n_jobs)
noise_raw.notch_filter([60,120,180], n_jobs=n_jobs)

# create epochs
evts, evtsid = mne.events_from_annotations(raw)
evtsid = {i:j for i,j in evtsid.items() if i in conds_OI} 
epo = mne.Epochs(raw, 
                 preload=True, 
                 tmin=epo_tmin, 
                 tmax=epo_tmax, 
                 baseline=epo_baseline, 
                 events=evts,
                 event_id = evtsid, 
                 reject = reject_dict)

#%% Auto reject
epo.load_data()
epo.pick_types(meg=True, ref_meg=False)
ar = AutoReject(n_interpolate=[1, 4, 8], 
                picks='meg', 
                random_state=0,
                n_jobs=n_jobs, 
                consensus=[0.8, 0.9, 1.0], 
                cv=5,
                )
cleaned_epo, reject_log = ar.fit_transform(epo, return_log=True)

cleaned_epo_bidspath = preprocessing_path.copy().update(extension='.fif', 
                                             run=run, session=ses, description='arCleanedEpo')
cleaned_epo.save(str(cleaned_epo_bidspath.fpath))

epo = cleaned_epo



#%% Perform the beamformer actions
def normalize_beamfilt_ori(fwd, filters):
    src = fwd['src']
    src_anat_ori = np.vstack([i['nn'][i['vertno']] for i in src])
    ori_flip = np.sign(np.sum(filters['max_power_ori'] * src_anat_ori, axis=1))
    filters['weights'] *= ori_flip[:,np.newaxis]
    filters['max_power_ori'] *= ori_flip[:,np.newaxis]
    
# compute ICA 

# Create cov
full_cov = mne.compute_covariance(epo[conds_OI], 
                                  cv=cov_cv, 
                                  method=cov_method)
full_cov_bidspath = output_path.copy().update(suffix='cov', 
                                              extension='.fif',
                                              description=f'EPOf{f_min}f{f_max}'
                                              )
full_cov_bidspath.fpath.parent.mkdir(parents=True, exist_ok=True)
full_cov.save(full_cov_bidspath.fpath, overwrite=overwrite_beam)
logger.info(f'Saved full covariance to: {full_cov_bidspath.fpath}')

noise_cov = mne.compute_raw_covariance(noise_raw)
noise_cov_bidspath = output_path.copy().update(suffix='cov', 
                                              extension='.fif',
                                              description=f'NOISEf{f_min}f{f_max}'
                                              )
noise_cov.save(noise_cov_bidspath.fpath, overwrite=overwrite_beam)
logger.info(f'Saved noise covariance to: {noise_cov_bidspath.fpath}')

# Make wts
filters = make_lcmv(epo.info, fwd, full_cov, noise_cov= noise_cov,
                    reg=beam_reg, pick_ori=beam_ori) #rank=epo_rank,
normalize_beamfilt_ori(fwd, filters)
filters_bidspath = output_path.copy().update(description=f'LCMVf{f_min}f{f_max}',
                                             extension='.h5', 
                                             suffix='lcmv')
filters.save(filters_bidspath.fpath, overwrite=overwrite_beam)
logger.info(f'Saved LCMV filters to: {filters_bidspath.fpath}')
# make_bids_json(filters_bidspath


stc_basename = output_path.copy().update(extension='.stc')
                                         
def stc_proc(epo, taskname, filters, return_abs=False, save_ave=True,
             save_epo=False, overwrite=True):
    _tmp_stcs = apply_lcmv_epochs(epo[taskname], filters, return_generator=True)
    _tmp_stcs = [i.apply_baseline([None,0]) for i in _tmp_stcs]
    _ave_stcs = copy.deepcopy(_tmp_stcs[0])
    _ave_stcs._data = np.mean(np.array([i._data for i in _tmp_stcs]), axis=0)
    
    if save_epo:
        pass  #set this up to iterate through epochs and save
    
    
    if save_ave:
        stc_bidspath = stc_basename.copy().update(description=f'{taskname}',
                                                  processing=f'f{f_min}f{f_max}')
        _ave_stcs.save(stc_bidspath)
        logger.info(f'Saved average STC to: {stc_bidspath.fpath}')
    return _tmp_stcs, _ave_stcs


for cond in conds_OI:
    _ = stc_proc(epo, cond, filters, save_ave=True, save_epo=True)
    
