name: nih2mne-tests
on: [push]
jobs:
  Pytest:
    name: InstallAndTest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
        mne-version: ["1.10"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
      - uses: actions/checkout@v4
        with:
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
      - name: Install MNE
        shell: bash -el {0}
        run: conda install --override-channels --channel=conda-forge 'python=${{ python-version }}' pytest 'mne=${{ mne-version }}'  
      - name: Install Git
        run: sudo apt install git -y
      - name: Pip Install nih2mne
        shell: bash -el {0}
        run: $CONDA/bin/pip install git+https://github.com/nih-megcore/nih_to_mne.git
      - name: Download test data
        shell: bash -el {0}
        run: make get_data
      - name: Pytest
        shell: bash -el {0}
        run: $CONDA/bin/pytest
  
